version: '3.2'
services:

  nodemanager:
    build:
      context: manager/app
      args:
        GRADLE_VERSION: "4.10.3"
        APP_PORT: 9200
    image: nodemanager
    container_name: nodemanager
    ports:
      - 9100:9100
      - 9090:9090