version: '2.3'

volumes:
  testnet-vol-1:
  testnet-vol-2:
  testnet-vol-3:
  testnet-nodemanager-volume:
  testnet-mongodb-volume:

services:

  node-1:
    build:
      context: core
      args:
        GRADLE_VERSION: "4.10.3"
        CORE_VERSION: "0.9.2"
        CORE_BRANCH: "master"
        CONF_NAME: "node-1-settings.conf"
    image: node-1
    container_name: testnet-node-1
    volumes:
      - testnet-vol-1:/apex
    ports:
      - 9091:9091
      - 8081:8081
    networks:
      testnet:
        ipv4_address: 172.28.1.1
    mem_limit: 2000m

  nodemanager:
    build:
      context: ../manager/app
      args:
        GRADLE_VERSION: "4.10.3"
        APP_PORT: 9110
    image: testnet-nodemanager
    container_name: testnet-nodemanager
    volumes:
      - testnet-nodemanager-volume:/root
    ports:
      - 9110:9110
      - 9090:9090
    networks:
      testnet:
        ipv4_address: 172.28.1.4
    mem_limit: 3000m

  mongodb:
    image: mongo
    container_name: testnet-mongo-db
    volumes:
      - testnet-mongodb-volume:/data/db
    expose:
      - 27017
    networks:
      - testnet
    mem_limit: 2000m

networks:
  testnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16